### ISSUE TITLE
chapterable components

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#1]
Chaptered content will be implemented as follows
- User will have a checkbox on Basic Content type with a label along the lines of "Add Table of Contents menu to page" 
- On the client, we will add anchor links (via something like https://www.bryanbraun.com/anchorjs/) to `h2`s based on the list of chapterable components below 
- On the client, we will generate the Table of Contents menu and add it to the page from those anchor links

https://docs.google.com/spreadsheets/d/13cmk4VZSI3R7wmOUB4L8JlvK5Ot0IPCL97_v-3N2LMQ/edit#gid=0

Chapterable? | Component Name |  
-- | -- | --
Yes | Text |  
Yes | Two Column Text |  
No | Image |  
No | Image with Text |  
No | Slideshow |  
No | Audio |  
No | Video |  
Yes | Curated Events |  
Yes | Related Basic Content |  
Yes | Upcoming Related Events |  
Yes | Related Stories |  
Yes | Frequently Asked Questions |  
Yes | Event Schedule |  
No | Embed |  
Yes | Profile List | need to discuss this one - assumes title for component is H2.
No | Social List |  
Yes | Spotlight Trio |  
No | Announcement |

**Comment by zebapy** [comment]
@kettlestitch @imcbride just to confirm again, we'll be adhering to the approach above, meaning **not** all components will have their h2 included in the chapter. Just want to record this here.

**Comment by kettlestitch** [comment]
That is my understanding.

________________________________

**Comment by imcbride** [comment]
That is my understanding of the discussion as well. Please also let me know if any content types other than Basic Content will be "chapterable".

**Comment by kettlestitch** [comment]
I believe it will only be basic content

________________________________
