### ISSUE TITLE
adjust columns for SA footer

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#103]
schools abroad footer needs 3 cols for schools menus, and 1 col for quick links

**Comment by zebapy** [comment]
@imcbride do you have a suggestion as to how we make quick links `col-sm-4` but our schools `col-sm-8` for the footer? I see both menus share the same col class in https://github.com/middlebury/drupal8/blob/master/web/themes/custom/school_theme/templates/block--menu-block--footer-nav.html.twig#L8

**Comment by imcbride** [comment]
Yes, if that class needs to change I will just create a copy of the template file in web/themes/custom/schools_abroad_theme. Or, I can make that class name into a variable and write a hook_preprocess_block() function in the .theme file to supply it. Either way, not a big deal to override a class name on the child theme.

**Comment by zebapy** [comment]
I've updated the school footer to show what I'm talking about https://github.com/middlebury/midd-frontend/commit/881dd1468de5b092067887e6e478f994e525f9a6

If it's problematic to have different classes per footer menu, let me know.
