### ISSUE TITLE
schools abroad admissions (and others) main nav item should be dropdown

### ISSUE THREAD

**Issue by Aterkel** [middlebury/midd-frontend#117]
With the exception of "Our Schools", no other top level menu items have dropdowns. This means a user must click twice to get to a second level page. For example, if a user wants to get to "Financial Aid" they would have to click "Admissions" then "Financial Aid" from the Admissions Page as opposed to being able to click once on "Financial Aid" through a dropdown on "Admissions".

Does this make sense? And is this how we want it to work?

Thoughts?

**Comment by zebapy** [comment]
I agree in the context of SA, items that have many children could benefit from having dropdowns in the primary navigation.

**Comment by zebapy** [comment]
Seems like @kettlestitch went ahead and did this.
