### ISSUE TITLE
caps title in page nav should be blue if current page

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#162]
On this page https://www.middlebury.edu/office/study-abroad/before-you-go since Before you Go is the active page, we should make the h2/caps text our active style

**Comment by zebapy** [comment]
@imcbride can we add the `page-nav__link--active` on this link when page is current? https://github.com/middlebury/drupal8/blob/master/web/themes/custom/middlebury_theme/templates/menu--left-nav.html.twig#L21

**Comment by imcbride** [comment]
Added in https://github.com/middlebury/drupal8/commit/343abf416bc22e72480b0f51a0c29a4b08d26892
