### ISSUE TITLE
library hours table issues on mobile

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#174]
https://www.middlebury.edu/library/about/hours

![Jun-25-2019 08-43-18](https://user-images.githubusercontent.com/2199845/60099284-5492c600-9725-11e9-851c-bcf0992c1b2e.gif)

**Comment by imcbride** [comment]
The Library wants to change the hours table so before doing any work on fixing this issue we need to have a meeting with them and @kettlestitch to nail down the requirements. If needed we can pull the data straight from the API and use whatever markup we want, or transform the markup SpringShare throws at us, but what's shown now isn't exactly what they want to show.

**Comment by kettlestitch** [comment]
Should we get requirements from the Library first, or should we meet and make a recommendation to them first?
________________________________

**Comment by imcbride** [comment]
They would like something like this https://middlebury.libguides.com/libcal-test

There is embed code for that, but its worth having a conversation with that to ensure we get all the details correct for it, or if we have a better suggestion, that's certainly worth floating.

**Comment by zebapy** [comment]
The original hours page mentioned in the issue now redirects to https://middlebury.libcal.com/hours/ which (for the most part) handles responsive styles for the hours
