### ISSUE TITLE
improve dropdown (non-navigation) menu keyboard controls

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#181]
https://inclusive-components.design/menus-menu-buttons/

As suspected, there are some recommendations to handle up/down/esc arrow keys and more in our `dropdown.js` (SA school explorer uses the dropdowns). 

- [ ] Need to investigate if there different recommendations for popup menus that contain a list of links

**Comment by poojagunturu96** [comment]
The dropdown menus have the recommended aria attributes and functionality mentioned in the article linked in this issue.
