### ISSUE TITLE
CourseHub-D8 theming

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#190]
Hi Zeb, Ari,

Thanks again for meeting together and participating in this project! 

You can log into my dev instance of the new Course Hub at
https://saw.middlebury.edu/~afranco/drupal/hubtest/

Use the login link in the sidebar or footer.

After logging in you can masquerade as an instructor or student. I’ve been testing with instructor “newbury” since he teaches the first course I happened to click on. After masquerading as him you can go to his dashboard at:
https://saw.middlebury.edu/~afranco/drupal/hubtest/dashboard/201990 

Pick one of the students in his class roster to get the student view.

The primary screens we discussed theming:
- [ ] Dashboard
    https://saw.middlebury.edu/~afranco/drupal/hubtest/dashboard/201990 
- [ ] A course group page
    https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/amst/0225a 
- [ ] Syllabus listing page
    https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/amst/0225a/syllabus 
- [ ] Resource listing page
    https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/amst/0225a/resources 
- [ ] Roster
    https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/amst/0225a/roster 
    - [ ] Print styles for roster
- [ ] The school/terms/subject browsing pages
    Example:  https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990 

Thanks again and let me know if you need anything further!

**Comment by zebapy** [comment]
@adamfranco Can you remind us what you were hoping to have from us by 8/21? Was that date correct?

**Comment by adamfranco** [comment]
Yep, hoping to have initial templates for the check-boxed items above (print styles could come later). And yes, that date is correct.

Also, I am regularly breaking my dev site, so I've put a more stable copy at https://saw.middlebury.edu/~afranco/drupal/hubtest/ and updated the links in this issue to reflect the new URLs.

Thanks!

**Comment by zebapy** [comment]
@adamfranco you'll have to be caught up on the numerous changes we've gone through but @Aterkel has designed some more custom elements for course hub. @imcbride and Joe have been kept in the loop and have seen the new designs.  

I've wrapped up the templates as far as I can tell with 2 known remaining items. 
- **masquerade form treatment** Joe mentioned this is a key feature for testing but we suggested using the default drupal UI for handling this in the mean time, until we can polish its placement/design (if needed). 
- **manage sections link** I know you spoke of calling this out or putting it in navigation. It hasn't been considered in the designs yet. 

I'm sure you'll have questions but you'll need to connect with @Aterkel (may want to do email or slack vs Github as I'm unsure how much he monitors these issues). I'll do my best to stay connected during my week off (won't be 100% occupied) if I need answer some questions. 

The code is on a new change here https://github.com/middlebury/midd-frontend/tree/coursehub-v2

**Comment by adamfranco** [comment]
Hi @zebapy & @Aterkel, @joeantonioli I've now implemented these templates in the Hub at they are visible at https://saw.middlebury.edu/~afranco/drupal/hubtest/

A few notes:

- I haven't yet implemented the chapter-nav output for the school-browsing page at https://saw.middlebury.edu/~afranco/drupal/hubtest/hub as I'm getting crunched on time and reworking this view is a little tricky. That can come later.

- On the full-width dashboard pages I shoved the login link and other controls in a grey bar below the content. See https://saw.middlebury.edu/~afranco/drupal/hubd8/dashboard . This is something that could be handled better than it is currently, but I wasn't sure what would be needed to output these more like the footer boxes on other sites.

- We still need to implement print styles for the Roster so that pages don't break in the middle of someone's face. Would also be good to condense the output to multi-column.

Please let me know if there are things that you notice that I've gotten wrong or interpreted incorrectly in translating the templates.

**Comment by JoeAntonioli** [comment]
![Screen Shot 2019-09-13 at 9 12 40 AM](https://user-images.githubusercontent.com/812853/64869893-495a8280-d610-11e9-86b3-73a6e2fe4deb.png)
Breadcrumb tail is redundant in reduced width view.

**Comment by adamfranco** [comment]
@JoeAntonioli Ari has pointed out that the breadcrumb shouldn't be including the current page. That is something I can fix and which will remove the redundancy.

**Comment by zebapy** [comment]
@adamfranco should I close this and we open specific issues if more come up?

**Comment by adamfranco** [comment]
Yep. Let's close this one.
