### ISSUE TITLE
create office site components

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#2]
- [x] Two Column Text
- [x] Frequently Asked Questions
- [x] Event Schedule
- [x] Image
- [x] Link List
- [x] Audio
- [ ] Video
- [ ] Image with Text
- [ ] Pull Quote
- [ ] Announcement
- [ ] Gallery
- [ ] Basic Chart
- [ ] Map Chart
- [ ] Social Media Feed
- [ ] Chaptered Video
- [ ] Curated Events
- [ ] Upcoming Related Events
- [ ] Related Stories
- [ ] Latest News
- [ ] Upcoming Events
- [ ] RSS Feed
- [x] Profile List
- [ ] Embed
- [ ] What's Your Mission
- [ ] Career Outcomes
- [ ] Spotlight (Institute vers)
- [ ] Spotlight (DP vers)
- [ ] Themed Panel
- [ ] Spotlight Trio
- [ ] What Interests You
- [ ] Schools and Programs Spotlight
- [ ] Mega CTA

**Comment by zebapy** [comment]
@kettlestitch can you confirm these?

**Comment by kettlestitch** [comment]
@zebapy -yes. We will have three additional from DP's designs (Ari hasn't finalized them yet). 

They are:
- [ ] Social Media Listing
- [ ] Spotlight Trio
- [ ] Announcement

**Comment by zebapy** [comment]
closing this in favor of individual issues for components
