### ISSUE TITLE
create roster print styles for course hub

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#203]
Need to prevent profile images from getting cut in half when printing. 

related to #190

**Comment by zebapy** [comment]
@adamfranco Would this suffice or are we looking for more print styles to say, hide navs, etc? I'm setting profiles to have `page-break-inside: avoid`

![Screenshot 2019-09-19 10 10 24](https://user-images.githubusercontent.com/2199845/65252345-cda47e00-dac6-11e9-9712-e39e31aef381.png)
![Screenshot 2019-09-19 10 10 29](https://user-images.githubusercontent.com/2199845/65252351-cf6e4180-dac6-11e9-90d6-9c169e3bb9db.png)

**Comment by adamfranco** [comment]
That is way better than what it was looking like. 👍  @JoeAntonioli what do you think?

**Comment by adamfranco** [comment]
The main improvement I could envision would be shrinking sizes and floating to two columns, but I'm not sure if this is necessary or not.

**Comment by zebapy** [comment]
I think if we were to do that we should maintain 2 columns on desktop then and we'd have to shift info to underneath images. At that point, I think @Aterkel would like to look at it. My vote would be leave it for now if we can unless there's further feedback pushing for it.

**Comment by JoeAntonioli** [comment]
With this feature are looking for a cheat sheet as they learn the names and faces of the students in their class, the more students we can fit on one page the better. Also helps with 2028 goals.

**Comment by zebapy** [comment]
We've taken a look at moving the profiles to a grid, so here is our first option. 

![localhost_3000_course-hub-roster html](https://user-images.githubusercontent.com/2199845/65628134-d6052900-df9e-11e9-8e67-20b20fcdcd42.png)

We're not saving a _ton_ of vertical space but it tightens it up a bit. We can push this further by either reducing the profile image size and/or reworking the meta info so it can be right of the image again but we wanted to start with this. If this works for you both, I'll wrap this up. Thanks.

**Comment by adamfranco** [comment]
The only remaining thing is that print styles aren't very usable.

On Mac/Firefox only the first two roster results display (partially) and the menus take up a full page:
![Screen Shot 2019-10-02 at 11 06 31 AM](https://user-images.githubusercontent.com/25242/66057405-a312e600-e506-11e9-856a-2fe5ef623093.png)

On Mac/Chrome all of the results display and the menus are more compact, but the photos get chopped across pages.
![Screen Shot 2019-10-02 at 11 18 29 AM](https://user-images.githubusercontent.com/25242/66057471-c473d200-e506-11e9-9178-dd3a2f805985.png)
