### ISSUE TITLE
Display issues with percent bar charts

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#228]
![Screen Shot 2019-11-12 at 11 06 19 AM](https://user-images.githubusercontent.com/662895/68688349-91c4ec80-053c-11ea-99d1-87fbe3ddab44.png)

Removing `flex-wrap: wrap` from `.percent-bar` resolves the issue with the lower bar chart, but there's still not enough padding between the percent labels for them to be legible.

Chart markup:

```
<div
  class="chart"
    data-chart="percentBar"
    data-datasets='[{"data":[25,50,1309,85]}]'
    data-labels='["Open","Pending","Closed","Customer Hold"]'
    data-title="" 
    data-y-label=""   data-x-label="Number of Tickets Opened this Month by Status at end of Month" 
    data-max=""   data-min="" 
    data-value-prefix=""   data-value-suffix="" ></div>
</div>

<div
  class="chart"
    data-chart="percentBar"
    data-datasets='[{"data":[20,29,2071,61]}]'
    data-labels='["Open","Pending","Closed","Customer Hold"]'
    data-title="" 
    data-y-label=""   data-x-label="Number of Tickets Opened this Month by Status at end of Month" 
    data-max=""   data-min="" 
    data-value-prefix=""   data-value-suffix="" ></div>
</div>
```

**Comment by zebapy** [comment]
There are two fixes off the bat we could apply to this. 

My initial thought was display a normal x axis with the 0-50-100 percentages then hover a color to see the exact amount (this functions like most of our charts)

![Screenshot 2019-11-12 11 28 11](https://user-images.githubusercontent.com/2199845/68690137-84f5c800-053f-11ea-8879-e9ec499a8e47.png)

@Aterkel's proposal is put the % right in the legend. 
![Screenshot 2019-11-12 11 27 46](https://user-images.githubusercontent.com/2199845/68690103-77d8d900-053f-11ea-926d-54d841b1f943.png)

@kettlestitch and @imcbride do you have any preference?

**Comment by imcbride** [comment]
I prefer Ari's approach since small values are more immediately legible to the viewer, but either solution would be fine with me.

**Comment by zebapy** [comment]
@imcbride there are extra closing `div` in the example markup you supplied. Are those in our templates somewhere? 

I agree on using Ari's version as it reads clearer.

**Comment by imcbride** [comment]
That was just a bad copy/paste on my part. Apologies.
