### ISSUE TITLE
Allow decimal places in the Chart - Big Number component

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#230]
The CountUp library allows decimal places with the syntax:

```
const options = {
  decimalPlaces: 2,
};
```

Could we add an optional attribute to the big number chart component allowing decimal places?

**Comment by zebapy** [comment]
I've added support for this on `countup-decimals` branch if you want to test with drupal or I can simply merge it.

**Comment by imcbride** [comment]
I've tested and it works fine for me. Thanks for implementing this.

Hard-coding it to two decimal places works for my current needs. I'll leave it up to you as to whether you want to anticipate needing 1 decimal place or more than two and implementing it now or waiting until we find a valid use case.
