### ISSUE TITLE
Course Hub Roster grid spacing

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#233]
Hi @zebapy , In testing, one instructor noticed that the roster grid sometimes gets white-space when the names wrap to extra lines as shown in this screen-shot of the [FMMC 0104A roster](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/fmmc/0104a/roster):
<img width="331" alt="Screen Shot 2019-11-15 at 11 20 01 AM" src="https://user-images.githubusercontent.com/25242/68959073-5f64fa80-079b-11ea-9406-255deb375723.png">

Any ideas on how best to fix this? I'm not sure if it is an issue with my markup or with the styles.

**Comment by zebapy** [comment]
So there seem to be few routes to go with this. 

1) We set a min-height to each profile which is presumptuous that we'll never encounter 3 line names even though at varying screen sizes you can make the name wrap to 3. Once a name wraps and exceeds the min height we'd set, it'd create that white space gap again. 😐 

2) use JS for some sort of masonry layout 👎 

3) Change the layout back to single column since it fits the same amount of content when printed and could remove some extra styles needed for the old school float layout (since we can't use flexbox due to print style problems with chrome and `break-inside`) 👍 

![Screenshot 2019-11-15 14 47 30](https://user-images.githubusercontent.com/2199845/68971187-fd19f300-07b6-11ea-88a9-67f8fb63e5eb.png)


![Screenshot 2019-11-15 14 47 55](https://user-images.githubusercontent.com/2199845/68971190-fee3b680-07b6-11ea-82ec-1034b612e289.png)

**Comment by adamfranco** [comment]
Thanks Zeb. I'll ping @JoeAntonioli for feedback.

**Comment by JoeAntonioli** [comment]
Faculty that have tested the new design have appreciated the two column layout, being able to see more students on one screen. Option #1 will handle most cases.

Is there a way to limit what is shown, with a "more" link to display overflow if desired?

**Comment by zebapy** [comment]
Ok, I'll stick to the 2 column. Can we reduce the profile image size? With setting a fixed height, I'm not finding an ideal height that works for possible 2-3 line names unless we reduce the image height. This would be to keep 2x2 profiles on pages _with_ preventing page breaks in the middle of a profile.

**Comment by adamfranco** [comment]
Here are some examples of rosters with the longest names (don't want to post them publicly here). The longest is 66 characters long, but only a few are longer than 45 characters. 

- 66 Characters: R... At the bottom of [INTD 1074B](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201510/intd/1074b/roster) (Masquerade as jisham@middlebury.edu ) -- 3 lines.
- 66 Characters: O... Another is on [BIOL 0392A](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/202020/biol/0392a/roster) (Masquerade as kathleend@middlebury.edu ) -- 2 lines.
- 64 Characters: F... Part way down [GEOG 0326A](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201890/geog/0326a/roster) (Masquerading as ldreiss@middlebury.edu ) --  3 lines.
- 53 Characters: A... Second line of [DPPG 8630A](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/miis/201628/dppg/8630a/roster) (Masquerading as takaha@middlebury.edu ) -- 2 lines
- 51 Characters: K... about halfway down  [ENVS 0112A](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/envs/0112a/roster) (Masquerading as lapin@middlebury.edu) -- 2 lines.
- 50 Characters: L... [ANTH 0103A](https://saw.middlebury.edu/~afranco/drupal/hubtest/hub/mcug/201990/anth/0103a/roster) (Masquerading as msherida@middlebury.edu) -- 2 lines.

I've checked a few more down the list and the two above that wrap to 3 lines are the only ones that do. All the rest of the names fit on at most two lines. Give this, it might be reasonable to plan on supporting 2 lines and just let the floating break for the 3-line case as it is so rare (2 students). I'm personally OK with shrinking images though.

**Comment by zebapy** [comment]
@JoeAntonioli do you foresee any issue reducing the photo size to something like this? This is so we can have the min height set to 400 and keep the profiles from being broken across printed pages. 

![Screenshot 2019-11-19 13 43 44](https://user-images.githubusercontent.com/2199845/69175969-c99ad980-0ad2-11ea-927a-1524082fec6c.png)

![Screenshot 2019-11-19 13 44 24](https://user-images.githubusercontent.com/2199845/69175966-c9024300-0ad2-11ea-8003-a40f07b41198.png)

**Comment by imcbride** [comment]
Small note on this: the images will be coming from the Directory which only has one image size: 200x200. We can, naturally, display that at 100x100 or whatever else, but the aspect ratio will always be 1:1 rather than 3:4.

**Comment by JoeAntonioli** [comment]
Based on Ian's comment do we need to reduce the photo size? If so that is fine as long as the people in the photos are recognizable.

**Comment by zebapy** [comment]
I'm seeing images come in on @adamfranco's hubtest site as large as 783x1006. Will this not be true once it goes live?

**Comment by adamfranco** [comment]
The images are coming from the online directory and the underlying files are of arbitrary pixel size (though generally should be square). The images themselves won't be changing, but the max size they are displayed at (via CSS) is what might change to make the layout work better.
