### ISSUE TITLE
Icons for ITS System Status report

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#236]
Mostly for @Aterkel:

In order to effectively show the status of systems on the ITS homepage, we would like to use some icons as a visual aid. We need at leave one green "service is available" icon and one red "service is unavailable" icon. A yellow "service is partially available" icon is a nice-to-have, but not a strict requirement.

In addition to the color of the icon, there should be some visual indicator of the state, such as a checkmark for "available" or an X for "unavailable".

Here is a mockup of the component to indicate how the icons will be used. Note: this is something of a Frankenstein's monster of several components' markup. If you also want to help improve the design of this, that'd be great, but I'm just looking for a minimum viable product by the end of the year and I'll need to get signoff from internal stakeholders, which I've yet to do.

![Screen Shot 2019-11-21 at 9 22 36 AM](https://user-images.githubusercontent.com/662895/69346714-3e8c2180-0c41-11ea-9d3c-449bea5e1fce.png)

Other examples:

https://www.bates.edu/helpdesk/system-status-main/

http://go.middlebury.edu/status

http://go.middlebury.edu/pingdom

**Comment by zebapy** [comment]
@Aterkel FYI we have checkmark and X icons already and I can use CSS to create the green/red/yellow shape if necessary.

**Comment by imcbride** [comment]
Thanks @zebapy, that would work for my purposes. In order to get around caching, the client is going to request a JSON string from Drupal with a timestamp query parameter which will return the statuses and I'll just some JS to set the icons, so if I can just do something like:

```
if (status == good) {
  icon.addClass('icon__status_up');
}
else {
  icon.addClass('icon__status_down');
}
```

That will be sufficient for my needs.

**Comment by zebapy** [comment]
That's fine. Do we want to store that JS in this repo? I'm happy to supply it. Also are stakeholders tied to the grid layout vs a list view?

**Comment by imcbride** [comment]
I'll store the JS in the Drupal project. It will only be used on one page and I can attach it to the component where it's needed.

On the design side, people liked the Bates example I provided above. My prototype is just something I threw together. If your group wants to make it better, I'm all for it and will defend whatever you create, but my goal is to get an MVP out the door by the end of the year and this doesn't need to take priority over other work you're doing.

Aside from the icons in the original request. That's something I do need.

**Comment by Aterkel** [comment]
I'll take a look at the layouts and making it more like Bates. The icons seem easy.

Thanks.

**Comment by imcbride** [comment]
Thanks @Aterkel. The screenshot doesn't quite capture how extensive the list of printers is, so to give a better sense, here's the full page:

http://saw.middlebury.edu/~imcbride/office/information-technology-services

**Comment by Aterkel** [comment]
Thanks. I imagine it has to be able to list tons of printers.

**Comment by zebapy** [comment]
I worked with Ari to do this in code and this is what we've settled. @imcbride do you have any concerns? 

![Screenshot 2019-11-22 11 31 16](https://user-images.githubusercontent.com/2199845/69443039-9b5c0a80-0d1b-11ea-96ca-25883f7f4cca.png)

**Comment by imcbride** [comment]
This looks great to me. Thanks for working on this.

**Comment by zebapy** [comment]
@imcbride do you think a legend would be helpful? To me it seems obvious that there's "something on", "something off", then warning is unclear what its true meaning is. Or perhaps show some description text in a tooltip on hover.

**Comment by imcbride** [comment]
I think the icons and colors are self-explanatory. There should be alt or aria-label text for each of the statuses, probably something along the lines of "Available", "Experiencing Issues", "Unavailable".
