### ISSUE TITLE
Graphics for ITS homepage project management feature

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#237]
The new ITS homepage will feature a quad story component highlighting three projects we're engaged in, modeled on how this component is used on the Midd2Midd site. For this, we need four graphics, to replace the Midd2Midd ones shown in the example below, though they don't need to be the same sizes.

1. Something that represents "Project Management Office" as a functional area.
2. Multi-Factor Authentication Project
3. PowerBI (Enterprise Reporting Software) Project
4. Monterey Interpretation Lab

Along with #236, this is the only other graphics / design request I anticipate for the ITS website project.

**Comment by imcbride** [comment]
I forgot to attach the example image in the previous message.

![Screen Shot 2019-11-15 at 10 43 45 AM](https://user-images.githubusercontent.com/662895/69366129-a7849100-0c63-11ea-8885-17d6451f13ac.png)

**Comment by zebapy** [comment]
Are the graphics @Aterkel supplied awaiting approval or can this be closed?

**Comment by imcbride** [comment]
The graphics supplied are great. This can be closed.
