### ISSUE TITLE
Provide setting to display data set labels in y-axis for horizontal bar charts

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#258]
Ideally, we would like the labels for each of the bars in this chart to display on the y-axis.

![Screen Shot 2020-01-29 at 11 53 36 AM](https://user-images.githubusercontent.com/662895/73378164-2b737e80-428e-11ea-8fbf-719e7a753e6e.png)

https://github.com/middlebury/drupal8/issues/1007

**Comment by zebapy** [comment]
This must be a bug since this should happen. I'll look into it soon.
