### ISSUE TITLE
coursehub nav dropdowns broken on tablet/mobile

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#275]
![Screenshot 2020-03-17 11 27 57](https://user-images.githubusercontent.com/2199845/76872145-659ade80-6842-11ea-861a-72f6cd42001d.png)

~~likely a minify issue affecting class specificity for the nav__sublist / nav-dropdown__menu class~~

this is caused by https://github.com/middlebury/drupal8/blob/master/web/themes/custom/coursehub_theme/css/menu.css

**Comment by zebapy** [comment]
@adamfranco this is caused by https://github.com/middlebury/drupal8/blob/master/web/themes/custom/coursehub_theme/css/menu.css

thoughts? Can we remove that css override? Or I guess I can bump up the width defined in this repo if it's needed.

**Comment by adamfranco** [comment]
Thanks, Zeb. Let me take a look at why I had added that...

**Comment by adamfranco** [comment]
I added a break-point to make the style override only apply on screen-sizes above 1024px. I also updated the selector to target just that last drop-down with the academic calender links that are a bit too wide otherwise. Let me know if you end up increasing the width and I can remove this override.
