### ISSUE TITLE
Make responsive image sizes for videos more clear

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#28]
https://github.com/middlebury/midd-frontend/blob/master/src/templates/paragraphs/video.twig#L7

Please include the image dimensions for each of the breakpoints used here.

**Comment by imcbride** [comment]
If it's the same as described here, feel free to close the issue.

https://github.com/middlebury/midd-frontend/blob/master/src/data/data.yml#L160

**Comment by zebapy** [comment]
Would you prefer image styles are same as MIIS to share config? We've adjusted breakpoints and I'm not certain how that'll impact image styles just yet..

**Comment by imcbride** [comment]
I'm fine with them changing to work with the new breakpoints, I just need to know exactly what each of the new dimensions are since entering those pixel dimensions is part of the CMS configuration.

**Comment by zebapy** [comment]
we can't have different image styles for when an image is on basic content vs top level, correct?

**Comment by zebapy** [comment]
These may have to come later as I don't have some designs. Is that ok?

**Comment by imcbride** [comment]
The video paragraph is set up right now to just use the same sizes as the Institute site uses, which should be fine for now.

**Comment by zebapy** [comment]
some notes for self:

- it is likely top level page will have wider image than basic content. I need to test if srcset loads appropriate image, how images differ, and if we're ok with loading the larger size as fallback.
- Top level (and maybe basic content) will need to center the image if it is smaller than recommended size. 
- Videos will use same size as image on top level (they will "violate" the main column) 
- how will these images work floated?

**Comment by zebapy** [comment]
@imcbride we're ok on video image styles, right?

**Comment by imcbride** [comment]
I've just deployed your video image styles to the Offices and Schools Abroad sites.

**Comment by zebapy** [comment]
Thank you! So image styles are stored in config, meaning you have to update all site configs if an image style changes? 😦

**Comment by imcbride** [comment]
Yes, unfortunately. This is the one pain point of Drupal's new configuration management system when working with multisite. There's a proposal to fix it, but it's still at the proposal stage. https://www.drupal.org/project/ideas/issues/2957423. We can automate some of it at the command line level, which is what I tried (unsuccessfully) to do today, but hopefully I'll learn some new tricks at DrupalCon.

**Comment by zebapy** [comment]
Ok good to know. 

Should this video thumb auto update with the new styles or do they need to be refetched somehow? https://www.middlebury.edu/schools-abroad/schools/brazil

**Comment by imcbride** [comment]
I've fixed an issue where the old image style was still being used in the template when the image is a thumbnail from the third-party video provider, rather than a custom splash image uploaded by the editor. I think there's still an issue where the thumbnail vimeo is giving us is smaller than we'd like. I'll look into whether we can get a larger version and, if so, how to handle the update. If I can't, we'll have to choose one of these options:

1. Upscale the image.
2. Leave it as is and tell editors that they'll need to provide custom images in cases like these.

**Comment by kettlestitch** [comment]
There's something about upscaling that appeals to me. The terrible image might be more incentive to replace it.

________________________________

**Comment by imcbride** [comment]
It is indeed the case that the thumbnail returned by Vimeo is smaller than the default width of the video component. The thumbnail URL is retrieved from the oEmbed data which, by default is 640px wide.

https://vimeo.com/api/oembed.json?url=https://vimeo.com/223331914

But Vimeo does provide thumbnails up to 1200px wide.

https://vimeo.com/api/oembed.json?url=https://vimeo.com/223331914&width=1200

I just need to figure out how to update the module to do this and test the other providers and get it to update existing thumbnails. This is a hot topic in the issue queue. https://www.drupal.org/project/issues/video_embed_field?text=thumbnail&status=Open&priorities=All&categories=All&version=All&component=All

**Comment by imcbride** [comment]
I've applied a patch from https://www.drupal.org/project/video_embed_field/issues/2954954 which will load larger Vimeo thumbnails for new video components. This won't update any existing video thumbnails and, in fact, if you delete a video the old thumbnail sticks around and will be used when you re-create it.

There's a patch for that issue at https://www.drupal.org/project/video_embed_field/issues/3009955, but there's an issue with this patch where if there's a duplicate video component, deleting one will delete the thumbnail for both, so I'll have to work on that before applying it.

**Comment by kettlestitch** [comment]
Delete the video means deleting the entire media bundle from the system? That won't work?

**Comment by imcbride** [comment]
Correct. Even if you delete the whole media bundle the thumbnail sticks around in the media table and will get re-used.

**Comment by kettlestitch** [comment]
Ugh.....

**Comment by imcbride** [comment]
Video thumbnails now update when you update the video bundle, so I believe this is now resolved.
