### ISSUE TITLE
Make responsive image sizes for image with text more clear

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#29]
https://github.com/middlebury/midd-frontend/blob/master/src/templates/paragraphs/image-with-text.twig#L3

Should this use the profile_spotlight_item (https://github.com/middlebury/midd-frontend/blob/master/src/data/data.yml#L176) size as it does on the institute site, or the 300x400 size shown here? In the latter case, what are the other breakpoints for the image, if any?

**Comment by zebapy** [comment]
Ok to close?
