### ISSUE TITLE
create content types

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#3]
> https://docs.google.com/spreadsheets/d/13cmk4VZSI3R7wmOUB4L8JlvK5Ot0IPCL97_v-3N2LMQ/edit#gid=0

for office site

- [x] Basic Content
- [ ] Newsroom
- [ ] Top Level (will be single office homepage)
- [ ] Chart
- [ ] Story
- [x] Event
- [x] Profile
- [x] ~Profile Listing~ use basic content with profile list component

other
- [ ] Center
- [ ] Program
- [ ] Audience
- [ ] Area of Focus
- [ ] Content Feature
- [ ] Library
- [ ] Homepage

**Comment by zebapy** [comment]
@kettlestitch can you confirm these?

**Comment by kettlestitch** [comment]
@zebapy - these are all correct. Open question on the homepage content type. We may actually need that one in orer to manage content on the homepage. I'm just not sure what our approach will be on that. @imcbride might have some thoughts.

**Comment by zebapy** [comment]
closing this in favor of individual issues for content types
