### ISSUE TITLE
Course Hub: Notification of pronounciation/profile edits.

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#300]
The new name pronunciation feature in the Hub https://github.com/middlebury/drupal8/issues/973 adds a user-editable profile to the Course Hub. Access to this profile is via a small link next to the login/logout links:
![Screen Shot 2020-04-30 at 9 28 00 AM](https://user-images.githubusercontent.com/25242/80716094-3cb66c00-8ac5-11ea-8361-5126704b016b.png)

In order to alert users of this new feature, some sort of in-application notification message should be displayed. This notification should:

- [ ] Be visible to users that haven't filled out this field or dismissed the notification.
- [ ] Allow the user to click to go to their profile
- [ ] Allow the user to dismiss the notification temporarily and be reminded later.
- [ ] Allow the user to dismiss the notification permanently.

This notification could be rendered on pages in their markup or displayed after an ajax request for user notifications. Either is fine.

Clicking to dismiss the notification should hide it in the current DOM and send an ajax request indicating the dismissal.

**Comment by zebapy** [comment]
> This notification could be rendered on pages in their markup or displayed after an ajax request for user notifications. Either is fine.

Not sure I'll be handling this piece unless you want me to work on the ajax side, which I'm happy to do. 

> Be visible to users that haven't filled out this field or dismissed the notification.

Also this item seems to be on your side / D8, correct? I can add an `{% if show_notification %}` wrapper around the needed markup but it will only be for demo purposes.

**Comment by zebapy** [comment]
Here's a suggestion (wireframe) for the alert. I can do the frontend on this if the general layout / actions work. It'll use our existing alert styles, icon, and buttons. 

<img width="884" alt="Screenshot 2020-05-01 13 17 44" src="https://user-images.githubusercontent.com/2199845/80826669-a2335700-8bb0-11ea-941a-8d2140c21240.png">

**Comment by adamfranco** [comment]
Looks good to me. 👍
