### ISSUE TITLE
Instutute profiles' course list key has extra space

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#399]
The **Courseses Taught** section of faculty profiles includes a key to designate courses taught in the current/upcoming term. An example can be seen at https://www.middlebury.edu/institute/people/mahabat-baimyrzaeva 

![Screen Shot 2021-09-01 at 9 29 31 AM](https://user-images.githubusercontent.com/25242/131680603-a9e8a3b5-85a6-44e4-976c-44192cef3cca.png)

It has a bit of extra space between the "Current term ●" and "Upcoming term(s) ○" items, which looks to be inherited from general <li> style rules.

![Screen Shot 2021-09-01 at 9 23 17 AM](https://user-images.githubusercontent.com/25242/131680732-aed784f8-4876-4b64-ae57-e0cdae4d8247.png)

I wonder also if some left padding/margin might make the key look like a bit more of a key. 🤷

**Comment by adamfranco** [comment]
Also, it appears that the indicator icons aren't showing for current/upcoming terms on the course entries themselves.

**Comment by poojagunturu96** [comment]
The new course list component has different labels for current/upcoming terms which should take care of the issues mentioned.
