### ISSUE TITLE
ALL: Handle the case where <h2>s are empty for the chaptered nav

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#439]
Right now this causes a JavaScript error on the page. See https://support.gmhec.org/TDNext/Apps/49/Tickets/TicketDet.aspx?TicketID=43656

`Uncaught DOMException: Document.querySelector: '#-1' is not a valid selector`

**Comment by adamfranco** [comment]
Another case in the offices site: https://support.gmhec.org/TDNext/Apps/49/Tickets/TicketDet.aspx?TicketID=65065

**Comment by poojagunturu96** [comment]
I updated the chaptered nav code to check if the heading ids start with alphabets or no. If they don't, they get appended with `section-` text which makes them a valid id and _shouldn't_ break the javascript.
