### ISSUE TITLE
Add a MIIS shield and MIIS wordmark SVG

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#455]
We would like a version of this page tailored to the Institute. To do that, we'll need a shield graphic appropriately sized to use in the top left along with a version of the wordmark to its right.

https://www.middlebury.edu/streaming/

**Comment by imcbride** [comment]
Updated this to note that the "Middlebury" text is also a graphic, so we'll need an Institute version of that as well.

**Comment by poojagunturu96** [comment]
Here's the MIIS shield and MIIS wordmark SVGs. Let me know if you need anything else. 
![miis-logo](https://user-images.githubusercontent.com/79096552/192829411-b5a40cf0-d4a6-4bbd-8880-f34a53dbddd7.svg)
![miis-shield](https://user-images.githubusercontent.com/79096552/192829414-f6985aa7-c534-46fd-9213-bdeb08268411.svg)

**Comment by poojagunturu96** [comment]
Here's the MIIS logo SVG with the workdmark on 3 lines
![miis-logo-3-lines (1)](https://user-images.githubusercontent.com/79096552/192834127-a61b736d-36f0-4894-90a1-b87c75af54fa.svg)

**Comment by poojagunturu96** [comment]
Here's the logo text
![miis-text](https://user-images.githubusercontent.com/79096552/192870161-1e484dc5-cbf1-4c98-9845-5321f61bf7d2.svg)

**Comment by imcbride** [comment]
Sorry for not specifying this sooner, but I will need the text as white type on a transparent background. The shield also seems to have colors inverted when I add it to the page. Any idea what's up with that?

![image](https://user-images.githubusercontent.com/662895/193055021-b82efad8-09eb-4768-8275-b824b8408123.png)
