### ISSUE TITLE
Add Social Icons to Departmental (gray) Footer

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#465]
Icons need to be saved to the frontend project, Ian can then add support in Drupal once the frontend part is done.

Issue for Drupal backend work: https://github.com/middlebury/drupal8/issues/2092 Notify Ian here when this issue is closed.

-------------

Via [TDX#77407](https://support.gmhec.org/TDNext/Apps/49/Tickets/TicketDet.aspx?TicketID=77407) from Ari.

https://www.figma.com/file/vb0guxhBwgqLfifTgMazqW/Icons?node-id=4%3A113&t=SLQUF85Hhk4OlAlA-1

Hi,
I've spoken with Andrew and now have the icons sorted out. I've added the icons to the Figma file. The new ones are Discord, TikTok, Pinterest, and Mastodon. And please list them so when they display, they display in the following order.

Discord
LinkedIn
Instagram
TikTok
YouTube
Mastodon
Pinterest
Facebook

Link to icons in Figma
https://www.figma.com/file/vb0guxhBwgqLfifTgMazqW/Icons?node-id=4%3A113&t=SLQUF85Hhk4OlAlA-1

Attached is a screen shot example of where these go.
![Screen Shot 2022-11-22 at 4 39 12 PM](https://user-images.githubusercontent.com/25242/205997345-73633957-fa19-4b14-83d2-3372defb9853.png)

Thanks,
Ari

**Comment by poojagunturu96** [comment]
Issue resolved in commits 78a52cc5c94fa35cd8770a5168d892f83eb752ce, fb7a7b4c56566b698e214918aa773e23e8d45867.
