### ISSUE TITLE
ALL: Excess spacing on Two-Column Text component

### ISSUE THREAD

**Issue by BlairKloman** [middlebury/midd-frontend#486]
Excessive spacing between this component and any component used before it.
![Screen Shot 2023-03-09 at 4 28 59 PM](https://user-images.githubusercontent.com/71784525/224167271-68a860c1-502b-445f-8add-f71ef9d21fa3.png)

**Comment by poojagunturu96** [comment]
Page where the issue occurs: https://www.middlebury.edu/language-schools/languages/spanish/graduate/master-arts-spanish
