### ISSUE TITLE
Homepage jitters when slowly scrolling

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#499]
When scrolling slowly the scroll position jitters and bounces around. ([video](https://midd.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=896b498d-427b-4a6f-8231-aff00102b72b) of the effect)

I would expect the homepage to scroll smoothly.

**Comment by adamfranco** [comment]
As noted in Slack: "I think it would make sense to snap in the scroll direction, but not snap in the reverse direction. For example, if you are scrolling down and hit the snap threshold, keep going to the top of the next panel. What was frustrating is that I tried scrolling down just a little bit and it snapped me back up (and vise versa)."

**Comment by poojagunturu96** [comment]
Issue fixed in 7b51a76de242c5cbeb44a753acf7f87aff01b96e.
