### ISSUE TITLE
INSTITUTIONAL: Text/link overlap at 1282px wide on homepage

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#508]
At certain window widths, the text & link of the four fluencies boxes, particularly the one on the right with longer text. Noted in Firefox at 1282px wide:
![Screenshot 2023-05-25 at 8 43 57 AM](https://github.com/middlebury/midd-frontend/assets/25242/e5437b31-d3fc-43ba-b0ba-0a90f948845e)

**Comment by poojagunturu96** [comment]
Issue resolved by commit [a59a59b](https://github.com/middlebury/midd-frontend/commit/a59a59ba4efc5aa09f802b5ccfa08f586bf35ac8).
