### ISSUE TITLE
Service Catalog theming

### ISSUE THREAD

**Issue by adamfranco** [middlebury/midd-frontend#54]
Thanks again @zebapy and Ari for discussing the design needs of this application. Here are the notes and task-items I captured:

- Drop-downs in top menus? Yes, will eventually will be a designed element when really needed, but for now the Service Catalog will use left nav for the sub-menu navigation of facets.

- Full-width content? Or always need a left sidebar? Maybe yes? Sometimes? TBD?
On the service page, start off with the support and documentation links in place of the sidebar nav (on left).

- Mostly will try to use existing styles, but will take a look at a few templates such as a listing and Service and see how the content works out.

- [ ] **Search:** Full site search will be expanded to include options to search current application/site or "All". Default to application. Search target will change based on selection (in-application search page vs www.middlebury.edu/search)

- [ ] **Service template** for the service content type. 

- [ ] **Listing template** for the listings/taxonomy term pages.

----

Content types and pages/views:

- Basic Content 

- Taxonomy page — list of terms in the taxonomy. [example](https://servicecatalog.middlebury.edu/service-lifecycle-status)

- Term page — list of services associated with the term. [example](https://servicecatalog.middlebury.edu/service-lifecycle-status/production)

- Service content. [example](https://servicecatalog.middlebury.edu/services/canvas)
   ![canvas_service_catalog_-_2019-01-29_16 22 56](https://user-images.githubusercontent.com/25242/51941296-3f1da800-23e2-11e9-9631-84104a55b209.png)

- Administrative contact page (listing services in a table)
   ![screenshot_2019-01-29 bob cole service catalog](https://user-images.githubusercontent.com/25242/51941427-8c9a1500-23e2-11e9-84b1-77a27ddc502c.png)

- Table of all administrative contacts of a type and what they are contacts for. https://servicecatalog.middlebury.edu/administrative-contact-roles/technical-contact
   ![screenshot_2019-01-29 administrative contacts by role service catalog](https://user-images.githubusercontent.com/25242/51941481-ba7f5980-23e2-11e9-9c93-d10b543346ed.png)

----

**Service schema**

![screenshot_2019-01-29 manage fields service catalog](https://user-images.githubusercontent.com/25242/51941905-b6a00700-23e3-11e9-87ac-72c6f7494b7d.png)

**Comment by zebapy** [comment]
@adamfranco I'm currently waiting on Ari to free up some time before I can regroup with him for the course hub work. I was thinking i'd take this opportunity to work on Service Catalog since it's a similar task. Is this something you'd still want soon or can push until some unknown date?

**Comment by adamfranco** [comment]
This isn't something I'm going to be able to tackle until the Course Hub is done, so we can push this to later at this point.

**Comment by adamfranco** [comment]
This is now out of date with the migration to TDX.
