### ISSUE TITLE
extra space in header of school basic content in firefox

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#55]
Running Firefox 65, there's extra white space between the header and breadcrumb on the initial page load http://saw.middlebury.edu/~zpykosz/midd-frontend/dist/school-basic-content.html

If you open the browser inspector, it collapses and doesn't re-appear. The issue doesn't seem to be present in Chrome.

![screen shot 2019-01-31 at 9 17 23 am](https://user-images.githubusercontent.com/662895/52059894-0e03bb80-2539-11e9-9cfd-7291d4a72277.png)

**Comment by zebapy** [comment]
@imcbride if you refresh that url, are you seeing the same problem?

**Comment by imcbride** [comment]
Yes. I can't get it to reliably do that on the initial page load, but after refresh it gets stuck in that position.

**Comment by zebapy** [comment]
Can you still reproduce the problem with the `onload` change?
