### ISSUE TITLE
Normalize markup for footer / banner widgets

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#682]
Since I won't be able to use different templates for each of the widgets that get placed in the Info Bar versus the Footer, it would be helpful for them to have the same markup in each place. In the footer, there's a wrapper around the items that looks like this:

```
<div class="office-footer" role="region" aria-label="Contact Information">
	<div class="container">
		<div class="office-footer__row">
			<div class="office-footer__col">

                                 <!-- Address, or contact info, or text, or links, or social links -->

                         </div>
                 </div>
        </div>
</div>
```

So it would be convenient if the Info Bar worked in a similar fashion within the wrapper elements:

```
<div class="info-bar {{info_bar_class}}">
  <div class="container">
     <!-- Address, or contact info, or text, or links, or social links -->
  </div>
</div>
```

You can see how this breaks down in the Drupal project. Here is the layout template which is the "wrapper". This can be different between the footer and the info bar. Here is the footer version https://github.com/middlebury/drupal/blob/master/web/modules/custom/middlebury_footer_layouts/layouts/footer_contact/layout--footer-contact.html.twig

And then each of the different types of element will have their own template. The markup for these unfortunately needs to be the same between the footer and info bar. You can see the full list here (the block--inline-block--footer.... templates) https://github.com/middlebury/drupal/tree/master/web/themes/custom/middlebury_theme/templates. Here's the link list one in particular https://github.com/middlebury/drupal/blob/master/web/themes/custom/middlebury_theme/templates/block--inline-block--footer-link-list.html.twig

**Comment by poojagunturu96** [comment]
My assumption was that this bar would work the same way as the other office hours bars that have been setup in Drupal this way: https://github.com/search?q=repo%3Amiddlebury%2Fdrupal%20office-hours&type=code, so I updated the office-hours.twig file to info-bar.twig and replaced all the occurrences of office-hours.twig to use info-bar.twig and I see that I forgot to delete the office-hours.twig file but that component isn't being used anywhere in the frontend code currently as it is replaced by info-bar.twig. Sorry if this caused any confusion. 

As the CCI bar uses similar styles as the other office-hours bars and the markup is pretty much the same, I think it makes sense to reuse the same component for the CCI bar and have it setup as the other bars in Drupal, and update the name/classes of all the bars to the ones in info-bar.twig. 
But if we want to keep them separate, I can create a separate component for the CCI bar and keep office-hours.twig as is. Hope this makes sense and I hope I'm understanding the issue correctly.

**Comment by imcbride** [comment]
That was an entirely reasonable assumption on your part, but the difference with this one is that we've been asked to make it editable through the Drupal UI, so I need to allow for editable blocks, side-by-side, within the container. Since this has similar use cases to the footer blocks, I was hoping to reuse those. I have alternative options if that's not possible, but I was hoping it would be.

**Comment by poojagunturu96** [comment]
Aaah okay, I missed the part about making it editable. That makes sense, I can update the markup for it so it is the same as the footer markup.
