### ISSUE TITLE
hide first tier of page-nav items except active item

### ISSUE THREAD

**Issue by zebapy** [middlebury/midd-frontend#70]
also need to restyle active page link to be caps to match design

![Screenshot 2019-03-27 10 36 41](https://user-images.githubusercontent.com/2199845/55084992-44167500-507c-11e9-8b8a-fcf40962d7ae.png)

**Comment by zebapy** [comment]
@imcbride can we do something like the following?

```html
<nav aria-labelledby="">
<h2 id=""><a>Student Activities</a></h2>
<ul>...</ul>
</nav>
```

This makes more sense to me for a screen reader.

**Comment by imcbride** [comment]
Yes, the top-level nav can have different markup than its child navs.

**Comment by zebapy** [comment]
Sorry I'm confused when you say top-level. This would be on all basic content sidebar navigations.

**Comment by imcbride** [comment]
Sorry for confusing this with the word "top". Each level of navigation in a menu can have its own markup. The menu items are supplied to the template as a nested array that the template loops through. So at each level the links in `items` can have different wrapping markup than the links in `items.children`.

**Comment by zebapy** [comment]
So if we do the above approach, can the backend prevent rendering the non active first tier items for the office? I believe that deviates from our original plan here.
