### ISSUE TITLE
Changes to STORY and STORY LIST

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/midd-frontend#76]
1. On STORY LIST we will render categories as part of the menu and display the menu in the left sidebar.

2. STORY also has left sidebar and will render the menu if it has one. If no menu exists, we will show the address box anyway (so the space will never be blank). We will also add breadcrumbs. We are NOT adding the back link.

**Comment by zebapy** [comment]
We've shipped these templates so I'm closing this.
