### ISSUE TITLE
OFFICE: Address block is not displaying in the gray box

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/midd-frontend#78]
On basic content:
https://www.middlebury.edu/office/midd2midd/middmentors

Address block is missing the gray box

**Comment by zebapy** [comment]
@imcbride can you look at this? It needs the wrapper https://github.com/middlebury/midd-frontend/blob/master/src/templates/anchor-basic-content.twig#L40-L50

**Comment by zebapy** [comment]
Looks like this was closed in https://github.com/middlebury/drupal8/commit/e42dec89e2fbd0c85702abeb2d43f94bb6a0ea23
