### ISSUE TITLE
headroom and headroom--top classes not applied when logged in

### ISSUE THREAD

**Issue by imcbride** [middlebury/midd-frontend#94]
I believe this is because line 42 of headroom.js checks to see if the admin toolbar exists and, if so, doesn't load the event listener.

![Screen Shot 2019-04-04 at 4 02 09 PM](https://user-images.githubusercontent.com/662895/55584839-410e2b00-56f3-11e9-8af3-3b88d48f8bb3.png)

**Comment by zebapy** [comment]
Ah yup. We're most likely changing the header to accommodate for the utility nav, so I should be able to remove that js and all the logic for the custom offset for school header.

**Comment by zebapy** [comment]
closed by https://github.com/middlebury/midd-frontend/commit/632462e52c4cfddf1550c2527caaab5363487328
