### ISSUE TITLE
OFFICE: text breaks in firefox when you resize the browser

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/midd-frontend#96]
Matt Kucher showed me a bug for the Midd2Midd office website - looks like it is only one firefox.

http://whatsmybrowser.org/b/H895UZ5

If you resize your browser the text columns do not move the way they should - text gets pinned to the right. (like they are stuck in a single column)

https://www.middlebury.edu/office/midd2midd

**Comment by kettlestitch** [comment]
![Midd2Midd_website_screenshot](https://user-images.githubusercontent.com/12157987/56059709-acc74800-5d32-11e9-8b1a-1a8a18d38ed3.JPG)


Adding screen shot

**Comment by zebapy** [comment]
<img width="860" alt="Screenshot 2019-04-15 08 45 21" src="https://user-images.githubusercontent.com/2199845/56133613-cfd44080-5f5a-11e9-9b62-6ca32ced1b52.png">

@imcbride Do you know where those 2 extra divs wrapping `.paragraphs` are coming from and if we can remove them?

Also @kettlestitch this is FF 60 which seems to be 1% traffic. Upgrading the browser to latest fixes the problem. I think the fix should be easy (removing those divs) but I just wonder where we stand with problems like this, supporting a modern browser but it's 6 versions behind.

**Comment by imcbride** [comment]
There was some boilerplate markup in the "group" template that added those wrapping divs around the content of group homepages. I've removed this.

**Comment by imcbride** [comment]
As for the browser version, lab and distributed machines are given Firefox ESR, which is currently at 60. I recommend we include the current ESR version in our list of supported browsers. https://www.mozilla.org/en-US/firefox/organizations/

**Comment by kettlestitch** [comment]
Agreed

________________________________

**Comment by zebapy** [comment]
I added Firefor ESR to our `browserlist` file so autoprefixer and JS will be compiled for it when necessary. The markup change did correct this (thanks @imcbride) so I'm closing this.
