### ISSUE TITLE
OFFICE: Add document icons where we know the link is a document

### ISSUE THREAD

**Issue by kettlestitch** [middlebury/midd-frontend#98]
Please add some sort of designation where we know the document is either:

PDF
Google Drive
Office 360

The editor should not have to do anything.

This should most likely be true on the SCHOOL site as well.

---
Design: https://share.goabstract.com/a4b80ce6-0655-4009-bf83-99701fada0fc

**Comment by imcbride** [comment]
I've transferred to midd-frontend. If you need me to add something like a class to the link based on it's URL / extension, let me know.

**Comment by zebapy** [comment]
@imcbride do you want to add classes to these links or should I use selectors based on href attribute?
